```yaml
workflows:
  flutter-app:
    name: Flutter App
    environment:
      flutter: stable
    scripts:
      - cd principal/Aplicación\ Fanygisa
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
```
